export const siteCopy = {
  "zh-CN": {
    meta: {
      title: "Aoryn | 可见的桌面 Agent 工作台",
      description:
        "Aoryn 是一个面向 Windows 的桌面 Agent 工作台，把对话、执行、截图和运行历史放进同一块清晰舞台。",
    },
    localeName: "中文",
    langSwitch: "EN",
    nav: {
      capabilities: "能力",
      experience: "界面",
      download: "下载",
      register: "创建账号",
    },
    hero: {
      eyebrow: "Windows 桌面 Agent 工作台",
      title: "把桌面执行\n做成一块可见舞台。",
      body:
        "Aoryn 把对话、执行、截图与历史收进同一块界面，让自动化不再像一段失控脚本。",
      primaryCta: "下载 Windows 安装包",
      secondaryCta: "创建账号",
    },
    heroStage: {
      ariaLabel: "Aoryn hero stage",
      windowLabel: "Aoryn 工作台",
      modeLabel: "可见桌面执行面板",
      status: "可见执行",
      sideTitle: "当前流",
      sideItems: ["对话到执行", "Windows 感知", "运行历史保留"],
      focusLabel: "执行舞台",
      focusTitle: "任务在运行时，界面仍然保持清楚。",
      focusBody: "执行、截图、检查点与人工接管都挂在同一块产品表面里。",
      lanes: [
        {
          title: "历史始终跟随",
          body: "步骤和截图不离开当前任务。",
        },
        {
          title: "校正始终在手边",
          body: "显示器与 DPI 校正始终在手边。",
        },
      ],
      floatCards: [
        {
          eyebrow: "本地优先",
          title: "本机优先运行",
          body: "配置、记录和缓存都贴着当前机器工作。",
        },
        {
          eyebrow: "可见控制",
          title: "人工接管保持顺手",
          body: "需要暂停、继续或检查时，不必离开当前界面。",
        },
      ],
    },
    capabilities: {
      eyebrow: "核心能力",
      title: "把复杂桌面任务压缩成更短的理解链路。",
      body: "只保留三个判断 Aoryn 的核心角度。",
      items: [
        {
          note: "01",
          title: "可见执行",
          body: "从提问到结果，重要状态都留在画面里，不把 Agent 藏进黑箱。",
        },
        {
          note: "02",
          title: "本地优先",
          body: "配置、截图、历史与缓存围绕本机工作，更适合真实桌面环境。",
        },
        {
          note: "03",
          title: "Windows 感知",
          body: "显示器、工作区和 DPI 识别结果可以直接查看，也可以手动修正。",
        },
      ],
    },
    experience: {
      eyebrow: "产品界面",
      title: "运行中的系统，应该比静态说明更有说服力。",
      body:
        "Aoryn 不把执行藏起来；它把状态、显示器识别和历史记录留在同一块工作表面。",
      points: [
        "同一块界面里完成提问、执行与回看。",
        "运行历史和截图与当前任务保持同一上下文。",
        "显示器和 DPI 结果可以被直接核对与纠正。",
      ],
      stage: {
        ariaLabel: "Aoryn workspace showcase",
        windowLabel: "执行表面",
        status: "布局稳定",
        railLabel: "表面",
        railItems: ["对话规划", "运行中任务", "显示纠正"],
        panelLabel: "当前焦点",
        panelTitle: "任务继续推进时，状态仍然清晰可读。",
        panelBody: "这不是一张截图堆成的说明页，而是一块正在工作的产品表面。",
        cards: [
          { title: "运行记忆", value: "历史持续保留" },
          { title: "显示核对", value: "识别结果可校对" },
          { title: "人工接管", value: "接管不打断上下文" },
        ],
        footerLabel: "循环",
        footerValue: "可继续、可暂停、可回看",
      },
    },
    download: {
      eyebrow: "下载",
      title: "一个清楚的安装入口，就够开始。",
      body: "官网、安装包与运行入口已经连成一条干净链路。",
      primaryCta: "下载 Aoryn",
      secondaryCta: "创建账号",
      labels: {
        version: "版本",
        platform: "平台",
        size: "大小",
      },
    },
    register: {
      eyebrow: "账号",
      title: "把账号入口留在同一块产品表面上。",
      body: "保持轻量的注册入口，给同步、团队设备与远程控制能力留好位置。",
      items: ["轻量账号入口", "同一套产品语言", "继续保持下载优先"],
      cta: "打开注册表单",
      modalTitle: "创建你的 Aoryn 账号",
      modalBody: "注册入口已经准备好。你可以继续用同一套界面完成后续接入。",
      form: {
        name: "姓名",
        namePlaceholder: "请输入你的姓名",
        email: "邮箱",
        emailPlaceholder: "you@company.com",
        password: "密码",
        passwordPlaceholder: "至少 8 位字符",
        confirmPassword: "确认密码",
        confirmPasswordPlaceholder: "再次输入密码",
        acceptTerms: "我同意 Aoryn 的产品条款与隐私说明。",
        submit: "创建账号",
        submitting: "正在创建账号...",
        close: "关闭",
        successFallback: "注册入口已经准备好。",
        successLive: "你的注册请求已提交。",
        networkError: "当前无法连接注册服务，请稍后再试。",
      },
      validation: {
        nameRequired: "请输入姓名。",
        nameShort: "姓名至少需要 2 个字符。",
        emailRequired: "请输入邮箱地址。",
        emailInvalid: "请输入有效的邮箱地址。",
        passwordRequired: "请输入密码。",
        passwordShort: "密码至少需要 8 位字符。",
        confirmRequired: "请再次输入密码。",
        confirmMismatch: "两次输入的密码不一致。",
        acceptRequired: "请先勾选同意条款。",
      },
    },
    faq: {
      eyebrow: "FAQ",
      title: "最后两个问题。",
      body: "保持简短，但把最关键的点说清楚。",
      items: [
        {
          question: "现在只支持 Windows 吗？",
          answer: "是的。当前产品和公开安装包都聚焦在 Windows 桌面环境。",
        },
        {
          question: "下载前必须先注册吗？",
          answer: "不需要。安装包公开可下载，账号入口是独立的产品入口。",
        },
      ],
    },
    footer: {
      tagline: "为 Windows 桌面任务提供可见、可继续的执行表面。",
      copyright: "Aoryn",
    },
  },
  "en-US": {
    meta: {
      title: "Aoryn | A visible desktop agent workspace",
      description:
        "Aoryn is a Windows desktop agent workspace that keeps chat, execution, screenshots, and run history on one legible surface.",
    },
    localeName: "English",
    langSwitch: "中文",
    nav: {
      capabilities: "Capabilities",
      experience: "Experience",
      download: "Download",
      register: "Create account",
    },
    hero: {
      eyebrow: "Windows desktop agent workspace",
      title: "Turn desktop execution\ninto a visible stage.",
      body:
        "Aoryn brings chat, execution, screenshots, and history into one surface so automation no longer feels like a runaway script.",
      primaryCta: "Download for Windows",
      secondaryCta: "Create account",
    },
    heroStage: {
      ariaLabel: "Aoryn hero stage",
      windowLabel: "Aoryn Workspace",
      modeLabel: "Visible desktop run surface",
      status: "Visible run",
      sideTitle: "Current flow",
      sideItems: ["Prompt to action", "Windows-aware detection", "Run memory"],
      focusLabel: "Run stage",
      focusTitle: "The task stays clear while it is moving.",
      focusBody: "Execution, screenshots, checkpoints, and handoff all stay on the same product surface.",
      lanes: [
        {
          title: "History stays attached",
          body: "Steps and screenshots remain attached to the active task.",
        },
        {
          title: "Correction stays close",
          body: "Display and DPI correction stay within immediate reach.",
        },
      ],
      floatCards: [
        {
          eyebrow: "Local-first",
          title: "Runs stay grounded on device",
          body: "Config, history, and cache stay close to the machine doing the work.",
        },
        {
          eyebrow: "Visible control",
          title: "Human handoff stays natural",
          body: "Pause, continue, or inspect without leaving the current surface.",
        },
      ],
    },
    capabilities: {
      eyebrow: "Core capabilities",
      title: "Compress desktop complexity into a shorter chain of understanding.",
      body: "Three ideas are enough to understand what Aoryn is for.",
      items: [
        {
          note: "01",
          title: "Visible execution",
          body: "Important states stay on screen instead of disappearing into an opaque automation loop.",
        },
        {
          note: "02",
          title: "Local-first behavior",
          body: "Config, screenshots, history, and cache stay grounded in the machine doing the task.",
        },
        {
          note: "03",
          title: "Windows-aware control",
          body: "Monitor, work-area, and DPI results can be inspected directly and corrected when needed.",
        },
      ],
    },
    experience: {
      eyebrow: "Product surface",
      title: "A running system should be more convincing than a static explanation.",
      body:
        "Aoryn keeps execution visible by leaving state, display detection, and history on one working surface.",
      points: [
        "Ask, run, and review from the same interface.",
        "Run history and screenshots stay attached to the task in front of you.",
        "Display and DPI results can be checked and corrected directly.",
      ],
      stage: {
        ariaLabel: "Aoryn workspace showcase",
        windowLabel: "Execution Surface",
        status: "Stable layout",
        railLabel: "Surface",
        railItems: ["Chat planning", "Live run", "Display correction"],
        panelLabel: "Current focus",
        panelTitle: "The system stays legible while the task keeps moving.",
        panelBody: "This is not a page of disconnected screenshots. It is a product surface that still looks alive.",
        cards: [
          { title: "Run memory", value: "History persists" },
          { title: "Display check", value: "Detection stays reviewable" },
          { title: "Manual handoff", value: "Control returns without friction" },
        ],
        footerLabel: "Loop",
        footerValue: "Continue, pause, review",
      },
    },
    download: {
      eyebrow: "Download",
      title: "A clean installer entry point is enough to begin.",
      body: "The website, installer, and product entry now sit on one clear path.",
      primaryCta: "Download Aoryn",
      secondaryCta: "Create account",
      labels: {
        version: "Version",
        platform: "Platform",
        size: "Size",
      },
    },
    register: {
      eyebrow: "Account",
      title: "Keep the account entry on the same product surface.",
      body: "A light account entry leaves room for sync, team devices, and remote control related features.",
      items: ["Lightweight account entry", "Shared product language", "Download stays primary"],
      cta: "Open registration",
      modalTitle: "Create your Aoryn account",
      modalBody: "The account entry is ready. The same interface can carry the next service connection.",
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "you@company.com",
        password: "Password",
        passwordPlaceholder: "At least 8 characters",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Repeat your password",
        acceptTerms: "I agree to the Aoryn product terms and privacy notice.",
        submit: "Create account",
        submitting: "Creating account...",
        close: "Close",
        successFallback: "The registration entry is ready.",
        successLive: "Your registration request was submitted.",
        networkError: "We could not reach the signup service. Please try again.",
      },
      validation: {
        nameRequired: "Please enter your name.",
        nameShort: "Please enter at least 2 characters.",
        emailRequired: "Please enter your email address.",
        emailInvalid: "Please enter a valid email address.",
        passwordRequired: "Please create a password.",
        passwordShort: "Password must be at least 8 characters.",
        confirmRequired: "Please confirm your password.",
        confirmMismatch: "Passwords do not match.",
        acceptRequired: "Please accept the terms to continue.",
      },
    },
    faq: {
      eyebrow: "FAQ",
      title: "Two last questions.",
      body: "Keep the page light, but answer the important things.",
      items: [
        {
          question: "Is Aoryn Windows-only right now?",
          answer: "Yes. The current product and public installer both focus on a Windows desktop environment.",
        },
        {
          question: "Do I need an account before downloading?",
          answer: "No. The installer is public, while the account entry stays separate.",
        },
      ],
    },
    footer: {
      tagline: "A visible execution surface for real Windows desktop work.",
      copyright: "Aoryn",
    },
  },
};
