export const siteCopy = {
  "zh-CN": {
    meta: {
      title: "Aoryn | 本地优先的桌面 Agent 工作台",
      description:
        "Aoryn 是一个面向 Windows 的本地优先桌面 Agent 工作台，把对话、执行、截图和运行记录放进同一个可见界面。",
    },
    localeName: "中文",
    langSwitch: "EN",
    announcement: "Windows 安装包现已公开下载",
    nav: {
      capabilities: "能力",
      experience: "界面",
      download: "下载",
      faq: "FAQ",
      register: "注册",
    },
    hero: {
      eyebrow: "本地优先桌面 Agent 工作台",
      title: "让桌面执行看起来像产品，而不是一段自动化脚本。",
      body:
        "Aoryn 把对话、执行、截图与运行记录收进一个轻量工作台，让 Windows 桌面任务保持可见、可控、可继续。",
      primaryCta: "下载 Windows 安装包",
      secondaryCta: "创建账号",
      availability: "当前主入口是公开安装包，账号系统将作为下一阶段能力接入。",
      labels: ["Windows 10 / 11", "公开下载安装", "本地优先运行"],
    },
    heroOrbital: {
      ariaLabel: "Aoryn hero stage",
      status: "可见执行",
      title: "对话、执行、截图、历史",
      body: "一个更安静、更高级的首页入口，用来承接真正的桌面执行产品。",
      cards: [
        {
          title: "对话到执行",
          body: "先明确目标，再把任务交给桌面执行流。",
        },
        {
          title: "运行保持可见",
          body: "步骤、截图与状态快照始终挂在同一条链路上。",
        },
      ],
      tags: ["Windows 感知", "本地优先", "公开下载", "混合控制"],
    },
    capabilities: {
      eyebrow: "核心能力",
      title: "把复杂执行压缩成更清楚的产品层级。",
      body: "首页只保留最值得被看见的部分，能力说明也只讲真正影响产品判断的三件事。",
      items: [
        {
          note: "01",
          title: "可见执行",
          body: "从提问到运行结果，关键节点都能回看，不把 Agent 隐藏在不可解释的流程里。",
        },
        {
          note: "02",
          title: "本地优先",
          body: "配置、截图、运行记录和缓存都贴着本机环境工作，更适合桌面自动化语境。",
        },
        {
          note: "03",
          title: "Windows 感知",
          body: "显示器、工作区和 DPI 会被识别出来，并允许用户手动校正。",
        },
      ],
    },
    experience: {
      eyebrow: "产品舞台",
      title: "真正的价值，在于它看起来就像一个正在工作的系统。",
      body:
        "Aoryn 不把执行藏起来。它让运行过程、环境识别和手动接管点都保持在同一块表面上，便于你理解、检查和继续推进。",
      bullets: [
        "一个界面内完成提问、执行与回看",
        "截图、步骤与状态快照持续可见",
        "显示器与 DPI 结果可以直接核对并手动纠正",
      ],
      signals: [
        { value: "可见", label: "执行状态" },
        { value: "GUI + DOM", label: "混合控制" },
        { value: "本地", label: "本机数据面" },
      ],
      preview: {
        ariaLabel: "Aoryn workspace preview",
        windowLabel: "Aoryn 工作台",
        windowMeta: "桌面 Agent 界面",
        status: "运行可见",
        railLabel: "当前层级",
        railItems: ["对话规划", "Agent 执行", "运行历史", "显示识别"],
        chips: ["可见步骤", "实时截图", "Windows 几何信息"],
        focusLabel: "当前状态",
        focusTitle: "任务在运行时依然清晰，不会变成黑箱。",
        focusBody: "界面不强调炫技，而是强调每一步仍然可以被人类理解、检查和接管。",
        currentTaskLabel: "当前任务",
        currentTask: "打开目标站点，从当前可见状态继续执行。",
        checkpointLabel: "检查点",
        checkpoint: "显示器、工作区与浏览器状态已采集。",
        metrics: [
          { value: "单任务", label: "稳定执行" },
          { value: "显示感知", label: "环境识别" },
          { value: "历史保留", label: "运行记录" },
        ],
        footerLabel: "下一步",
        footerValue: "继续执行，或在当前状态下人工接管。",
      },
    },
    download: {
      eyebrow: "下载安装",
      title: "今天先从一个干净的安装入口开始。",
      body:
        "当前公开版本保持简单直接：一个正式下载地址、一个清晰官网入口，以及为后续账号体系预留好的产品位。",
      primaryCta: "下载主安装包",
      secondaryCta: "创建账号",
      labels: {
        version: "版本",
        platform: "平台",
        packageType: "安装包类型",
        fileSize: "文件大小",
        hosting: "托管方式",
        release: "文件名",
      },
      notes: [
        "安装时支持自定义程序目录。",
        "配置保存在 %APPDATA%\\Aoryn。",
        "运行记录、截图和缓存保存在 %LOCALAPPDATA%\\Aoryn。",
      ],
    },
    register: {
      eyebrow: "注册入口",
      title: "账号入口已经准备好，后面只需要接上你的后端。",
      body:
        "下载仍然是第一优先级，注册是更轻的辅助入口。前端交互、校验和成功态都已经准备好，后续只替换接口即可。",
      cta: "打开注册表单",
      benefits: [
        "面向 aoryn.org 的正式产品注册入口",
        "不改页面结构即可接入真实注册服务",
        "保留清晰的成功态、失败态与校验反馈",
      ],
      modalTitle: "创建你的 Aoryn 账号",
      modalBody:
        "当前版本已经完成产品化表单和校验逻辑。等你的后端接口准备好后，可以直接接到同一套提交流程中。",
      form: {
        name: "姓名",
        namePlaceholder: "请输入你的姓名",
        email: "邮箱",
        emailPlaceholder: "you@company.com",
        password: "密码",
        passwordPlaceholder: "至少 8 位字符",
        confirmPassword: "确认密码",
        confirmPasswordPlaceholder: "再次输入密码",
        acceptTerms: "我同意 Aoryn 的产品条款与隐私说明。",
        submit: "创建账号",
        submitting: "正在创建账号...",
        close: "关闭",
        successFallback: "注册前端已经准备完成。下一步只需要接入你的后端接口。",
        successLive: "注册请求已提交成功。",
        networkError: "当前无法连接注册服务，请稍后重试。",
      },
      validation: {
        nameRequired: "请输入姓名。",
        nameShort: "姓名至少需要 2 个字符。",
        emailRequired: "请输入邮箱地址。",
        emailInvalid: "请输入有效的邮箱地址。",
        passwordRequired: "请输入密码。",
        passwordShort: "密码至少需要 8 位字符。",
        confirmRequired: "请再次输入密码。",
        confirmMismatch: "两次输入的密码不一致。",
        acceptRequired: "请先勾选同意条款。",
      },
    },
    faq: {
      eyebrow: "最后几个问题",
      title: "在下载之前，把最关键的点说清楚。",
      body: "保持简洁，不把首页重新变成一份冗长说明书。",
      items: [
        {
          question: "现在只支持 Windows 吗？",
          answer: "是的。当前产品和公开安装包都聚焦于 Windows 桌面环境。",
        },
        {
          question: "必须先注册才能下载吗？",
          answer: "不需要。安装包公开可下载，注册是独立的后续入口。",
        },
        {
          question: "用户数据保存在哪里？",
          answer: "配置保存在 %APPDATA%\\Aoryn，运行记录、截图和缓存保存在 %LOCALAPPDATA%\\Aoryn。",
        },
      ],
    },
    footer: {
      tagline: "本地优先的桌面 Agent 工作台，让执行过程保持可见、可调试、可继续。",
      copyright: "Aoryn",
    },
  },
  "en-US": {
    meta: {
      title: "Aoryn | Local-first desktop agent workspace",
      description:
        "Aoryn is a local-first desktop agent workspace for Windows, bringing chat, execution, screenshots, and run history into one visible interface.",
    },
    localeName: "English",
    langSwitch: "中文",
    announcement: "Public Windows installer available now",
    nav: {
      capabilities: "Capabilities",
      experience: "Experience",
      download: "Download",
      faq: "FAQ",
      register: "Create account",
    },
    hero: {
      eyebrow: "Local-first desktop agent workspace",
      title: "Make desktop execution feel like a product, not a script.",
      body:
        "Aoryn brings chat, execution, screenshots, and run history into a calmer surface for real Windows work.",
      primaryCta: "Download for Windows",
      secondaryCta: "Create account",
      availability: "The public installer is live today. Account services are the next layer.",
      labels: ["Windows 10 / 11", "Public download", "Local-first runs"],
    },
    heroOrbital: {
      ariaLabel: "Aoryn hero stage",
      status: "Visible execution",
      title: "Chat, runs, screenshots, history",
      body: "A cleaner landing page for a product that is supposed to act, not just answer.",
      cards: [
        {
          title: "Chat to agent",
          body: "Clarify the goal first, then hand off to real desktop execution.",
        },
        {
          title: "Runs stay visible",
          body: "Steps, screenshots, and checkpoints remain attached to the same flow.",
        },
      ],
      tags: ["Windows aware", "Local-first", "Download ready", "Hybrid control"],
    },
    capabilities: {
      eyebrow: "Core capabilities",
      title: "A simpler hierarchy for a more serious product.",
      body: "The homepage only keeps what matters most: visible execution, local-first behavior, and Windows-aware control.",
      items: [
        {
          note: "01",
          title: "Visible execution",
          body: "From prompt to result, the important states stay inspectable instead of disappearing behind automation.",
        },
        {
          note: "02",
          title: "Local-first behavior",
          body: "Config, runs, screenshots, and cache stay grounded in the local machine where desktop work actually happens.",
        },
        {
          note: "03",
          title: "Windows-aware correction",
          body: "Monitor, work-area, and DPI detection can be shown to users and corrected when needed.",
        },
      ],
    },
    experience: {
      eyebrow: "Product stage",
      title: "The value is in how legible the system remains while it is working.",
      body:
        "Aoryn keeps the loop understandable. Runs, screenshots, environment signals, and handoff points stay on one surface instead of being hidden behind a black box.",
      bullets: [
        "Ask, run, and review from the same interface",
        "Screenshots, steps, and state snapshots stay visible",
        "Display and DPI detection can be checked and corrected manually",
      ],
      signals: [
        { value: "Live", label: "Execution state" },
        { value: "GUI + DOM", label: "Hybrid control" },
        { value: "Local", label: "On-device data" },
      ],
      preview: {
        ariaLabel: "Aoryn workspace preview",
        windowLabel: "Aoryn workspace",
        windowMeta: "Desktop agent surface",
        status: "Run visible",
        railLabel: "Current stack",
        railItems: ["Chat planning", "Agent execution", "Run history", "Display detection"],
        chips: ["Visible steps", "Screenshots", "Windows geometry"],
        focusLabel: "Workspace state",
        focusTitle: "The task stays legible while the agent is moving.",
        focusBody: "The interface is meant to feel calm, readable, and easy to trust while work is happening.",
        currentTaskLabel: "Current task",
        currentTask: "Open the target site and continue from the visible state.",
        checkpointLabel: "Checkpoint",
        checkpoint: "Monitor, work-area, and browser state already captured.",
        metrics: [
          { value: "Single-task", label: "Reliable flow" },
          { value: "Monitor aware", label: "Display detection" },
          { value: "History kept", label: "Run memory" },
        ],
        footerLabel: "Next step",
        footerValue: "Continue execution, or hand control back to the user.",
      },
    },
    download: {
      eyebrow: "Download",
      title: "Start with one clean Windows entry point.",
      body:
        "The public release stays intentionally simple: one installer, one polished site, and a clear place for the future account layer.",
      primaryCta: "Download installer",
      secondaryCta: "Create account",
      labels: {
        version: "Version",
        platform: "Platform",
        packageType: "Package",
        fileSize: "Size",
        hosting: "Hosting",
        release: "Filename",
      },
      notes: [
        "The install directory can be customized during setup.",
        "Configuration is stored in %APPDATA%\\Aoryn.",
        "Runs, screenshots, and cache are stored in %LOCALAPPDATA%\\Aoryn.",
      ],
    },
    register: {
      eyebrow: "Account",
      title: "The account entry point is ready. The backend can arrive later.",
      body:
        "Download remains the primary conversion path. Registration stays secondary, with the UI, validation, and success states already prepared.",
      cta: "Open registration",
      benefits: [
        "A proper account entry point for aoryn.org",
        "Ready to connect to a real signup service later",
        "Keeps success, failure, and validation states product-ready",
      ],
      modalTitle: "Create your Aoryn account",
      modalBody:
        "This version already includes the product-facing form and validation flow. When your backend is ready, the same submission path can be reused.",
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "you@company.com",
        password: "Password",
        passwordPlaceholder: "At least 8 characters",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Repeat your password",
        acceptTerms: "I agree to the Aoryn product terms and privacy notice.",
        submit: "Create account",
        submitting: "Creating account...",
        close: "Close",
        successFallback: "The registration frontend is ready. Connect your backend endpoint next.",
        successLive: "Your registration request was submitted successfully.",
        networkError: "We could not reach the signup service. Please try again.",
      },
      validation: {
        nameRequired: "Please enter your name.",
        nameShort: "Please enter at least 2 characters.",
        emailRequired: "Please enter your email address.",
        emailInvalid: "Please enter a valid email address.",
        passwordRequired: "Please create a password.",
        passwordShort: "Password must be at least 8 characters.",
        confirmRequired: "Please confirm your password.",
        confirmMismatch: "Passwords do not match.",
        acceptRequired: "Please accept the terms to continue.",
      },
    },
    faq: {
      eyebrow: "A few practical answers",
      title: "Keep the homepage clear, but answer the important questions.",
      body: "Enough detail to remove friction, without turning the landing page back into a document.",
      items: [
        {
          question: "Is Aoryn Windows-only right now?",
          answer: "Yes. The current product and public installer both focus on a Windows desktop environment.",
        },
        {
          question: "Do I need an account before downloading?",
          answer: "No. The installer is public. Registration is a separate future-facing product entry point.",
        },
        {
          question: "Where does Aoryn store user data?",
          answer: "Configuration stays under %APPDATA%\\Aoryn, while runs, screenshots, and cache stay under %LOCALAPPDATA%\\Aoryn.",
        },
      ],
    },
    footer: {
      tagline: "A local-first desktop agent workspace for visible, debuggable execution.",
      copyright: "Aoryn",
    },
  },
};
